export const ICALC_APP_VERSION = 'ICALC_APP_PLACEHOLDER';
export const ICALC_DOMAIN_VERSION = 'ICALC_DOMAIN_PLACEHOLDER';
export const KOPLA_APP_VERSION = 'KOPLA_APP_PLACEHOLDER';
export const KOPLA_DOMAIN_VERSION = 'KOPLA_DOMAIN_PLACEHOLDER';
