import { NgModule } from '@angular/core';
import {
  AboutModule,
  CardModule,
  CardWrapperModule,
  ContactFormModule,
  CookiePolicyModule,
  FeatureFlagModule,
  FooterModule,
  HeaderModule,
  HttpModule as KoplaHttpModule,
  InfoModule,
  LiabilityDisclaimerModule,
  MenuConfigurationManagementModule,
  CultureSelectModule,
  MenuCultureSelectModule,
  MenuModule,
  MenuShoppingCartModule,
  NavbarModule,
  NotificationModule,
  OverlayModule,
  PanelModule,
  StageModule,
  StepperModule,
  StorageModule,
  SvgModule,
  ToolbarModule,
} from '@igus/kopla-app';
import { TranslateModule } from '@ngx-translate/core';

@NgModule({
  declarations: [],
  imports: [TranslateModule],
  exports: [
    TranslateModule,
    FeatureFlagModule,
    SvgModule,
    NavbarModule,
    NotificationModule,
    StepperModule,
    ToolbarModule,
    FooterModule,
    HeaderModule,
    MenuModule,
    ContactFormModule,
    InfoModule,
    CardModule,
    CardWrapperModule,
    LiabilityDisclaimerModule,
    PanelModule,
    OverlayModule,
    KoplaHttpModule,
    StorageModule,
    CookiePolicyModule,
    AboutModule,
    MenuConfigurationManagementModule,
    MenuShoppingCartModule,
    MenuCultureSelectModule,
    CultureSelectModule,
    FeatureFlagModule,
    StageModule,
  ],
})
export class KoplaAppModule {}
